import type { Metadata } from "next";
// import localFont from "next/font/local";
import { EB_Garamond } from 'next/font/google'
import "../globals.css";
import BackgroundVesting from "./backgroundVesting"

const ebGaramond = EB_Garamond({
  subsets: ['latin'],
  display: 'swap',

})

// const regFont = localFont({
//   src: "../fonts/EBGaramond12-AllSC.ttf",
//   display: "swap"
// })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased relative min-h-screen w-full ${ebGaramond.className}`}
      >
        <BackgroundVesting />
        <main className="z-10">{children}</main>
      </body>
    </html>
  );
}


// ${geistSans.variable} ${geistMono.variable} 
